framework:
    translator: { fallback: en }

imports:
    - { resource: doctrine_extensions.yml }

parameters:

    carbon_api.upload_dir: "%kernel.root_dir%/../uploads"
    frontend_password_reset_url: "%frontend.url%/user/password-reset/confirm"
    jms_serializer.serialized_name_annotation_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
        filters:
            softdeleteable:
                class: "Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter"
                enabled: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: "Carbon\\ApiBundle\\Entity\\User"
    resetting:
        email:
            template: CarbonApiBundle:user:password_reset.html.twig
            from_email:
                address: %mailer_user%
                sender_name: %app.name%

uecode_api_key:
    delivery: header #or header
    parameter_name: apikey # defaults to `api_key`

oneup_uploader:
    mappings:
        profile:
            frontend: blueimp # or any uploader you use in the frontend
            namer: carbon_api.upload_namer
            storage:
                service:              ~
                type:                 filesystem
                filesystem:           ~
                directory:            %carbon_api.upload_dir%/profile
                stream_wrapper:       ~
                sync_buffer_size:     100K

jms_serializer:

     metadata:

        debug: "%kernel.debug%"

        auto_detection: false

        directories:
            test:
                path: "@CarbonApiBundle/Resources/config/serializer"
