Carbon\ApiBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
          expose: true
          groups: [default]
        username:
          expose: true
          groups: [default]
        email:
          expose: true
          groups: [default]
        avatarAttachment:
          expose: true
          groups: [default]
        firstName:
          expose: true
          groups: [default]
        lastName:
          expose: true
          groups: [default]
        createdAt:
          expose: true
          groups: [default]
        updatedAt:
          expose: true
          groups: [default]
        last_login:
          expose: true
          groups: [default]
        enabled:
          expose: true
          groups: [default]
    virtual_properties:
        getFullName:
            serialized_name: fullName
            expose: true
            type: string
            groups: [default]
        getStringLabel:
            serialized_name: stringLabel
            expose: true
            type: string
            groups: [default]
        getRoles:
            serialized_name: fullName
            expose: true
            type: array
            groups: [default]
